function buildToolbar(obj, parent)
    %BUILDTOOLBAR The handful of things done over and over, one click away.
    % Nothing here is new: every button is an item of the Plot or Data
    % menu, or one of the two buttons at the foot of the panel. They
    % are repeated over the plot because settling on a figure means
    % copying it, looking at it, and changing something a dozen times
    % over, and a menu is two clicks each time round.

    % Text, tooltip, and what the button does. A row with no callback
    % is the gap between one group of buttons and the next.
    buttons = { ...
        "Copy plot", "Copy the plot to the clipboard as an image.", ...
            @() obj.copyPlot(); ...
        "Copy vector", "Copy the plot to the clipboard as vector " + ...
            "graphics, which stay sharp however large they are printed.", ...
            @() obj.copyPlot(ContentType = "vector"); ...
        "Save plot...", "Write the plot to a PNG, PDF, SVG, or .fig file.", ...
            @() obj.savePlot(); ...
        "", "", []; ...
        "Copy data", "Copy the drawn profiles to the clipboard, " + ...
            "one column per section.", ...
            @() obj.onCopyData(); ...
        "Copy summary", "Copy a written account of every choice " + ...
            "behind this view: the scale, what is shown, split, and filtered.", ...
            @() obj.copySummary(); ...
        "Copy code", "Copy the commands that put a browser back in " + ...
            "this view, ready to paste into a script.", ...
            @() obj.onCopyCommands(); ...
        "To workspace", "Put the numbers behind the plot in the " + ...
            "base workspace.", ...
            @() obj.onSendToWorkspace(); ...
        "", "", []; ...
        "Pop out", "Draw this view into an ordinary figure window.", ...
            @() obj.popOut(); ...
        "Reset", "Put the depth window, the scale, and the filter back.", ...
            @() obj.onReset()};

    isGap = cellfun(@isempty, buttons(:,3));

    widths = repmat({'fit'}, 1, size(buttons, 1));
    widths(isGap) = {11};

    % One trailing column takes whatever room is left, so the buttons
    % stay together at the left rather than spreading over the width.
    grid = uigridlayout(parent, [1 numel(widths) + 1]);
    grid.ColumnWidth = [widths, {'1x'}];
    grid.RowHeight = {'1x'};
    grid.ColumnSpacing = 4;
    grid.Padding = [0 0 0 0];

    for k = 1:size(buttons, 1)

        if isGap(k)
            divider(grid, k);
            continue
        end

        button = uibutton(grid, ...
            Text = buttons{k,1}, ...
            Tooltip = buttons{k,2}, ...
            ButtonPushedFcn = @(~,~) buttons{k,3}());
        button.Layout.Column = k;

    end

end

function divider(grid, column)
    %DIVIDER A hairline between one group of buttons and the next.
    % The gap alone read as one long row of buttons that happened to be
    % unevenly spaced. A line in the middle of the gap says which of them
    % go together, and is drawn as a panel of its own inside the column
    % because a panel is sized by its parent rather than by a width of
    % its own.

    slot = uigridlayout(grid, [1 1]);
    slot.Layout.Column = column;
    slot.ColumnWidth = {1};
    slot.RowHeight = {'1x'};
    slot.Padding = [5 4 5 4];

    % Painted rather than bordered: a panel one pixel wide has nowhere to
    % put a border but on top of itself, and comes out as nothing at all.
    uipanel(slot, BorderType = "none", BackgroundColor = [0.72 0.72 0.72]);

end
