function buildUI(obj)
    %BUILDUI Lay out the controls beside the plot.
    % The panel holds two dozen controls, which is more than a window of
    % ordinary height can show at once and far more than any one figure is
    % made of. They are gathered into named sections that open and close, so
    % that the three or four a given figure is actually being settled by are
    % on screen together and the rest are one click away rather than several
    % turns of a scroll wheel. A closed section says in a few words what it
    % is holding, so nothing quietly narrows the plot from out of sight.

    obj.Fig = uifigure(Name = "ECM Browser", Position = [80 80 1400 860]);

    obj.buildMenus();

    % Controls beside the plot, and one status line under both of them:
    % what is on screen is as true of the plot as of the panel, and a line
    % at the foot of the panel is a line at the bottom of a scroll region,
    % which is to say a line no one reads.
    layout = uigridlayout(obj.Fig, [2 2]);
    layout.ColumnWidth = {300, '1x'};
    layout.RowHeight = {'1x', 38};
    layout.RowSpacing = 6;

    controls = uipanel(layout, BorderType = "none");

    % The plot, with the toolbar above it. The two share a column of
    % their own so that REFRESH can empty the plot panel without
    % taking the buttons over it down with the plot.
    plotColumn = uigridlayout(layout, [2 1]);
    plotColumn.ColumnWidth = {'1x'};
    plotColumn.RowHeight = {26, '1x'};
    plotColumn.RowSpacing = 4;
    plotColumn.Padding = [0 0 0 0];

    obj.buildToolbar(plotColumn);
    obj.PlotPanel = uipanel(plotColumn, BorderType = "none");

    obj.buildStatusBar(layout);

    depth = obj.Data.grid.depth;

    r = obj.SectionRowHeight;

    % One row per section. Each is sized to its own contents by ADDSECTION,
    % so the heights seeded here are placeholders; the panel scrolls for the
    % case of every section being opened at once.
    obj.SectionGrid = uigridlayout(controls, [7 1]);
    obj.SectionGrid.ColumnWidth = {'1x'};
    obj.SectionGrid.RowHeight = repmat({obj.SectionHeaderHeight}, 1, 7);
    obj.SectionGrid.RowSpacing = 6;
    obj.SectionGrid.Padding = [4 4 4 4];
    obj.SectionGrid.Scrollable = "on";

    % --- What is measured, and on what scale -----------------------------

    scale = obj.addSection(1, "scale", "Signal & scale", repmat({r}, 1, 5));

    obj.SignalDropDown = obj.addRow(scale, "Signal", ...
        @() uidropdown(scale, Items = ["smoothed", "raw"]));

    obj.NormalizeDropDown = obj.addRow(scale, "Normalize", ...
        @() uidropdown(scale, Items = obj.NormalizeModes, ...
            Tooltip = "Rescale the intensities before they are drawn."));

    obj.ScopeDropDown = obj.addRow(scale, "Scope", ...
        @() uidropdown(scale, Items = obj.NormalizeScopes, ...
            Tooltip = "How many sections share one scale."));

    obj.RefMinField = obj.addRow(scale, "Ref. min", ...
        @() uieditfield(scale, "numeric", Value = floor(min(depth)), ...
            Tooltip = "Start of the depth window the normalization is taken from."));

    obj.RefMaxField = obj.addRow(scale, "Ref. max", ...
        @() uieditfield(scale, "numeric", Value = ceil(max(depth)), ...
            Tooltip = "End of that window, and of the band the baseline modes measure."));

    % --- One level of a field against another ----------------------------

    compare = obj.addSection(2, "compare", "Compare", ...
        [repmat({r}, 1, 3), {96}], false);

    obj.CompareDropDown = obj.addRow(compare, "Compare", ...
        @() uidropdown(compare, Items = obj.CompareOps, ...
            Tooltip = "Measure one value of a field against another " + ...
                "within the same subject, plate, or whatever else " + ...
                "is matched on below, and draw the comparison in " + ...
                "place of the sections behind it. a is the value " + ...
                "compared and b the reference: difference is a - b, " + ...
                "ratio a / b, log2 ratio log2(a / b), % change " + ...
                "100 (a - b) / b, and normalized difference " + ...
                "(a - b) / (a + b)."));

    obj.CompareFieldDropDown = obj.addRow(compare, "Compare by", ...
        @() uidropdown(compare, Items = [obj.NoField; obj.GroupFields], ...
            Tooltip = "The field whose values are measured against " + ...
                "each other."), ...
        @(~,~) obj.onCompareFieldChanged());

    obj.CompareRefDropDown = obj.addRow(compare, "Reference", ...
        @() uidropdown(compare, Items = cellstr(obj.NoField), ...
            Tooltip = "Which value of that field is b, the one the " + ...
                "others are measured against. A field whose values " + ...
                "are peers -- subject, say -- has no such value and " + ...
                "is compared within itself instead: each value " + ...
                "against every section of the match holding another, " + ...
                "or each two values against each other in turn."));

    obj.PairListBox = obj.addRow(compare, "Pair within", ...
        @() uilistbox(compare, Items = [obj.NoField; obj.FilterFields], ...
            Multiselect = "on", ...
            Tooltip = "Which fields two sections have to agree on " + ...
                "to be compared -- subject and plate, usually. " + ...
                "Sections that match on all of them are averaged " + ...
                "per side first, then the two sides compared. " + ...
                "Whatever the plot is tiled by or colored by is " + ...
                "matched on as well, whether or not it is named " + ...
                "here, so that no comparison spans a tile or a color."));

    % --- What is drawn, and over what depths -----------------------------

    shown = obj.addSection(3, "plot", "Plot", repmat({r}, 1, 7));

    obj.ShowDropDown = obj.addRow(shown, "Show", ...
        @() uidropdown(shown, Items = obj.ShowModes, ...
            Tooltip = "The profiles themselves, their group mean, or " + ...
                "one point per section -- in peak depth against peak " + ...
                "intensity, or in whichever summary of the curve the " + ...
                "Metric control names."));

    obj.MetricDropDown = obj.addRow(shown, "Metric", ...
        @() uidropdown(shown, Items = obj.SummaryMetrics, ...
            Tooltip = "The single number each section is summarized by " + ...
                "in the metric summary. Read off the curve on screen, " + ...
                "so the depth window, the signal, the normalization, " + ...
                "and a comparison all reach it."));

    obj.ErrorDropDown = obj.addRow(shown, "Error band", ...
        @() uidropdown(shown, Items = obj.ErrorBands, ...
            Tooltip = "What the shading around a group mean spans, and " + ...
                "what the bar through a metric summary's group spans. " + ...
                "The bootstrap interval makes no assumption about the " + ...
                "shape of the sections' spread and needs the " + ...
                "Statistics and Machine Learning Toolbox."));

    obj.SectionsCheckBox = uicheckbox(shown, ...
        Text = "Sections behind the mean", ...
        Value = true, ...
        ValueChangedFcn = @(~,~) obj.refresh());
    obj.SectionsCheckBox.Layout.Column = [1 2];

    obj.GroupDropDown = obj.addRow(shown, "Color by", ...
        @() uidropdown(shown, Items = [obj.NoField; obj.GroupFields]));

    obj.DepthMinField = obj.addRow(shown, "Depth min", ...
        @() uieditfield(shown, "numeric", Value = floor(min(depth)), ...
            Tooltip = "Start of the depth window drawn."));

    obj.DepthMaxField = obj.addRow(shown, "Depth max", ...
        @() uieditfield(shown, "numeric", Value = ceil(max(depth)), ...
            Tooltip = "End of the depth window drawn."));

    % --- How the sections in view are divided up -------------------------

    split = obj.addSection(4, "split", "Split", {150});

    obj.TileListBox = obj.addRow(split, "Tile by", ...
        @() uilistbox(split, Items = [obj.NoField; obj.GroupFields], ...
            Multiselect = "on", ...
            Tooltip = "Pick several to split on every combination of them: " + ...
                "the last runs across the columns, the rest down the rows."));

    % --- Which sections are drawn at all ---------------------------------

    narrow = obj.addSection(5, "filter", "Filter", ...
        [{r}, {120}, {r}, {r}, {78}, {r}], false);

    obj.FilterFieldDropDown = obj.addRow(narrow, "Filter by", ...
        @() uidropdown(narrow, Items = [obj.AllSections; obj.FilterFields], ...
            Tooltip = "Which field to narrow. Narrowing a second field " + ...
                "adds a condition beside the first rather than " + ...
                "replacing it, so several parameters can be filtered " + ...
                "on at once."), ...
        @(~,~) obj.onFilterFieldChanged());

    obj.FilterValuesListBox = uilistbox(narrow, ...
        Items = {}, ...
        Multiselect = "on", ...
        Tooltip = "Which of that field's values the condition names. " + ...
            "Empty until a field is picked above; putting every " + ...
            "value back takes the condition off the list.", ...
        ValueChangedFcn = @(~,~) obj.onFilterValuesChanged());
    obj.FilterValuesListBox.Layout.Column = [1 2];

    obj.FilterSenseDropDown = obj.addRow(narrow, "Keep/drop", ...
        @() uidropdown(narrow, Items = obj.FilterSenses, ...
            Tooltip = "Whether the values picked above are the ones " + ...
                "kept or the ones thrown out."), ...
        @(~,~) obj.onFilterValuesChanged());

    obj.FilterMatchDropDown = obj.addRow(narrow, "Combine", ...
        @() uidropdown(narrow, Items = obj.FilterMatches, ...
            Tooltip = "Whether a section has to satisfy every " + ...
                "condition below or any one of them."));

    obj.FilterListBox = obj.addRow(narrow, "Filters", ...
        @() uilistbox(narrow, Items = {}, ...
            Tooltip = "The conditions standing. Pick one to put the " + ...
                "controls above back on the field it names."), ...
        @(~,~) obj.onFilterSelected());

    uibutton(narrow, Text = "Remove", ...
        Tooltip = "Take the condition picked above off the list.", ...
        ButtonPushedFcn = @(~,~) obj.onRemoveFilter());
    uibutton(narrow, Text = "Clear all", ...
        Tooltip = "Drop every condition and draw the whole dataset.", ...
        ButtonPushedFcn = @(~,~) obj.onClearFilters());

    % --- How the grid of axes is dressed ---------------------------------

    dress = obj.addSection(6, "layout", "Layout", repmat({r}, 1, 7), false);

    obj.LegendDropDown = obj.addRow(dress, "Legend", ...
        @() uidropdown(dress, Items = obj.LegendPlacements, ...
            Tooltip = "One legend per plot, or one for the whole " + ...
                "figure placed outside the plots."));

    obj.SpacingDropDown = obj.addRow(dress, "Tile spacing", ...
        @() uidropdown(dress, Items = obj.TileSpacings, ...
            Tooltip = "How much room is left between one tile and the next."));

    obj.PaddingDropDown = obj.addRow(dress, "Padding", ...
        @() uidropdown(dress, Items = obj.LayoutPaddings, ...
            Tooltip = "How much room is left around the grid as a whole."));

    obj.TickLabelDropDown = obj.addRow(dress, "Tick labels", ...
        @() uidropdown(dress, Items = obj.TickLabelModes, ...
            Tooltip = "Which tiles carry the numbers on their axes. " + ...
                "Reading a tile in the middle off the edges of the " + ...
                "grid only holds while the axes are linked."));

    obj.LinkCheckBox = uicheckbox(dress, Text = "Link axes", Value = true, ...
        ValueChangedFcn = @(~,~) obj.refresh());
    obj.LinkCheckBox.Layout.Column = [1 2];

    obj.TransposeCheckBox = uicheckbox(dress, ...
        Text = "Transpose axes", ...
        Value = false, ...
        Tooltip = "Lay the axes out the other way round: the field " + ...
            "that ran across the columns runs down the rows.", ...
        ValueChangedFcn = @(~,~) obj.refresh());
    obj.TransposeCheckBox.Layout.Column = [1 2];

    obj.AxisQuantityCheckBox = uicheckbox(dress, ...
        Text = "Label depth/intensity too", ...
        Value = false, ...
        Tooltip = "The layout's axis labels name the Tile by " + ...
            "field(s) split across the grid. Check this to also " + ...
            "name the depth and intensity every tile plots, which " + ...
            "is otherwise left off as understood.", ...
        ValueChangedFcn = @(~,~) obj.refresh());
    obj.AxisQuantityCheckBox.Layout.Column = [1 2];

    % --- The panel above, saved under a name -----------------------------

    saved = obj.addSection(7, "config", "Configurations", repmat({r}, 1, 3), false);

    obj.ConfigDropDown = uidropdown(saved, Items = cellstr(obj.NoConfig), ...
        Tooltip = "Every control on this panel, saved under an " + ...
            "autogenerated name and kept from one session to the next.", ...
        ValueChangedFcn = @(~,~) obj.onConfigSelected());
    obj.ConfigDropDown.Layout.Column = [1 2];

    uibutton(saved, Text = "Save", ...
        Tooltip = "Save the panel as it is now under a new name.", ...
        ButtonPushedFcn = @(~,~) obj.onSaveConfig());
    uibutton(saved, Text = "Delete", ...
        Tooltip = "Remove the configuration named above.", ...
        ButtonPushedFcn = @(~,~) obj.onDeleteConfig());

    purgeButton = uibutton(saved, Text = "Purge all saved configs", ...
        ButtonPushedFcn = @(~,~) obj.onPurgeConfigs());
    purgeButton.Layout.Column = [1 2];

    % Nothing is filtered yet, so the value list and the keep/drop choice
    % both open with nothing to say and are grayed out until a field is
    % picked and a second condition asked for.
    obj.onFilterFieldChanged(false);
    obj.refreshFilterList();

    obj.applyDefaults();
    obj.refreshConfigList();

end
