function s = captureSettings(obj)
    %CAPTURESETTINGS Every control on the panel, as one struct.

    s = struct( ...
        Signal = string(obj.SignalDropDown.Value), ...
        Normalize = string(obj.NormalizeDropDown.Value), ...
        Scope = string(obj.ScopeDropDown.Value), ...
        RefMin = obj.RefMinField.Value, ...
        RefMax = obj.RefMaxField.Value, ...
        Compare = string(obj.CompareDropDown.Value), ...
        CompareField = string(obj.CompareFieldDropDown.Value), ...
        CompareRef = string(obj.CompareRefDropDown.Value), ...
        PairWithin = string(obj.PairListBox.Value), ...
        Show = string(obj.ShowDropDown.Value), ...
        Metric = string(obj.MetricDropDown.Value), ...
        ErrorBand = string(obj.ErrorDropDown.Value), ...
        SectionsBehind = obj.SectionsCheckBox.Value, ...
        Group = string(obj.GroupDropDown.Value), ...
        Tile = string(obj.TileListBox.Value), ...
        FilterMatch = string(obj.FilterMatchDropDown.Value), ...
        DepthMin = obj.DepthMinField.Value, ...
        DepthMax = obj.DepthMaxField.Value, ...
        Legend = string(obj.LegendDropDown.Value), ...
        TileSpacing = string(obj.SpacingDropDown.Value), ...
        Padding = string(obj.PaddingDropDown.Value), ...
        TickLabels = string(obj.TickLabelDropDown.Value), ...
        Link = obj.LinkCheckBox.Value, ...
        Transpose = obj.TransposeCheckBox.Value, ...
        AxisQuantity = obj.AxisQuantityCheckBox.Value);

    % Set beside the rest rather than among them: the filter is a list of
    % conditions, and a struct array handed to STRUCT is read as a request
    % for a struct array of settings rather than as one field holding it.
    s.Filters = obj.Filters;

end
