function buildDatasetMenu(obj)
%BUILDDATASETMENU Build the Dataset menu on the figure menu bar.
% The root folder, the tracker CSV, and the load action used to take a panel
% across the top of the window; they are chosen once per sitting, so they live
% on a menu now and the freed row goes to the catalog and the image tiles.
% uifigure menus ignore the Accelerator property, so the keys this menu offers
% are bound on the figure in ONFIGUREKEYPRESS and only named here.
%
% The tracker can come from three places, offered together because they suit
% different situations: the Sheets API is always current and is the only one a
% review can be written back to, the published copy is current and needs no
% credentials, and the CSV needs no network at all. ONLOADDATA reads them in
% that order and uses the first that is set.
%
% See also ONLOADDATA, ONEXPORTWORKSPACE, ONEDITFILENAMEPATTERN,
% ONCONFIGURESHEET, ONFIGUREKEYPRESS.

obj.DatasetMenu = uimenu(obj.Fig, Text = "Dataset");

obj.RootFolderMenu = uimenu(obj.DatasetMenu, ...
    Text = "Root Folder:  (none selected)", ...
    MenuSelectedFcn = @(~,~) obj.onBrowseRoot());

obj.MetadataMenu = uimenu(obj.DatasetMenu, ...
    Text = "Tracker CSV:  (none)", ...
    MenuSelectedFcn = @(~,~) obj.onBrowseMetadata());

obj.ClearMetadataMenu = uimenu(obj.DatasetMenu, ...
    Text = "Clear Tracker CSV", ...
    Enable = "off", ...
    MenuSelectedFcn = @(~,~) obj.onClearMetadata());

% How filenames are read decides what the catalog can be filtered and sorted
% by, so the convention is chosen here beside the folders it applies to and
% above the load that reads it.
obj.FilenamePatternMenu = uimenu(obj.DatasetMenu, ...
    Text = "Filename Pattern:  (built-in convention)", ...
    Separator = "on", ...
    MenuSelectedFcn = @(~,~) obj.onEditFilenamePattern());

% The tracker can also be read straight from the published copy of the sheet it
% is kept in, which saves exporting it by hand every time it changes, and needs
% no credentials to set up. It is read only, so a review still needs the API
% entry below it.
obj.PublishedSheetMenu = uimenu(obj.DatasetMenu, ...
    Text = "Published Sheet:  (none)", ...
    Separator = "on", ...
    MenuSelectedFcn = @(~,~) obj.onSetPublishedSheet());

obj.ClearPublishedSheetMenu = uimenu(obj.DatasetMenu, ...
    Text = "Clear Published Sheet", ...
    Enable = "off", ...
    MenuSelectedFcn = @(~,~) obj.onClearPublishedSheet());

obj.SheetMenu = uimenu(obj.DatasetMenu, ...
    Text = "Google Sheet Tracker", ...
    Separator = "on");

obj.SheetConfigureMenu = uimenu(obj.SheetMenu, ...
    Text = "Configure...", ...
    MenuSelectedFcn = @(~,~) obj.onConfigureSheet());

% Adding the two maintained columns changes the shape of a document other
% people edit, so it is something to choose rather than something a load does
% on its way past.
obj.SheetPrepareMenu = uimenu(obj.SheetMenu, ...
    Text = "Prepare Sheet for Writing...", ...
    Enable = "off", ...
    Separator = "on", ...
    MenuSelectedFcn = @(~,~) obj.onPrepareSheet());

obj.SheetClearMenu = uimenu(obj.SheetMenu, ...
    Text = "Clear Sheet Tracker", ...
    Enable = "off", ...
    MenuSelectedFcn = @(~,~) obj.onClearSheet());

obj.LoadMenu = uimenu(obj.DatasetMenu, ...
    Text = "Load Dataset" + obj.shortcutHint("loadDataset"), ...
    Separator = "on", ...
    MenuSelectedFcn = @(~,~) obj.onLoadData());

% Handing the selection to the workspace is something done to the data rather
% than to the view, so it belongs here beside the load rather than on Display
% next to the image export it shares a word with.
obj.ExportWorkspaceMenu = uimenu(obj.DatasetMenu, ...
    Text = "Export Selection to Workspace..." + obj.shortcutHint("exportWorkspace"), ...
    Separator = "on", ...
    MenuSelectedFcn = @(~,~) obj.onExportWorkspace());

% Placeholder labels are replaced as soon as the paths are known.
obj.refreshDatasetMenu();

end
