function buildDatasetMenu(obj)
%BUILDDATASETMENU Build the Dataset menu on the figure menu bar.
% The root folder, the tracker CSV, and the load action used to take a panel
% across the top of the window; they are chosen once per sitting, so they live
% on a menu now and the freed row goes to the catalog and the image tiles.
% uifigure menus ignore the Accelerator property, so the one key this menu
% offers is bound on the figure in ONFIGUREKEYPRESS and only named here.
%
% The tracker can come from a CSV export or from the Google Sheet the tracker
% actually lives in. Both are offered because they suit different situations:
% the sheet is always current and can be written back to, and the CSV works
% with no credentials and no network.

obj.DatasetMenu = uimenu(obj.Fig, Text = "Dataset");

obj.RootFolderMenu = uimenu(obj.DatasetMenu, ...
    Text = "Root Folder:  (none selected)", ...
    MenuSelectedFcn = @(~,~) obj.onBrowseRoot());

obj.MetadataMenu = uimenu(obj.DatasetMenu, ...
    Text = "Tracker CSV:  (none)", ...
    MenuSelectedFcn = @(~,~) obj.onBrowseMetadata());

obj.ClearMetadataMenu = uimenu(obj.DatasetMenu, ...
    Text = "Clear Tracker CSV", ...
    Enable = "off", ...
    MenuSelectedFcn = @(~,~) obj.onClearMetadata());

obj.SheetMenu = uimenu(obj.DatasetMenu, ...
    Text = "Google Sheet Tracker", ...
    Separator = "on");

obj.SheetConfigureMenu = uimenu(obj.SheetMenu, ...
    Text = "Configure...", ...
    MenuSelectedFcn = @(~,~) obj.onConfigureSheet());

% Adding the two maintained columns changes the shape of a document other
% people edit, so it is something to choose rather than something a load does
% on its way past.
obj.SheetPrepareMenu = uimenu(obj.SheetMenu, ...
    Text = "Prepare Sheet for Writing...", ...
    Enable = "off", ...
    Separator = "on", ...
    MenuSelectedFcn = @(~,~) obj.onPrepareSheet());

obj.SheetClearMenu = uimenu(obj.SheetMenu, ...
    Text = "Clear Sheet Tracker", ...
    Enable = "off", ...
    MenuSelectedFcn = @(~,~) obj.onClearSheet());

obj.LoadMenu = uimenu(obj.DatasetMenu, ...
    Text = "Load Dataset" + obj.shortcutHint("loadDataset"), ...
    Separator = "on", ...
    MenuSelectedFcn = @(~,~) obj.onLoadData());

% Placeholder labels are replaced as soon as the paths are known.
obj.refreshDatasetMenu();

end
