function buildDisplayPanel(obj, parent)
%BUILDDISPLAYPANEL Build the rendition, contrast, and overlay controls.

panel = uipanel(parent, Title = "Display");
panel.Layout.Row = 1;

% Every column is sized rather than stretchy, and the spacing is tighter than
% the default, because the rows of controls together are just wide enough to
% reach the right edge of the window at its opening size. Anything added here
% has to be paid for out of the widths below, which is why a new group of
% settings takes a row of its own rather than a column.
grid = uigridlayout(panel, [5 14]);
grid.RowHeight = {"fit", "fit", "fit", "fit", "fit"};
grid.ColumnWidth = {"fit", 92, "fit", 92, "fit", 92, "fit", 60, 60, "fit", 50, "fit", 100, 90};
grid.Padding = [8 8 8 8];
grid.RowSpacing = 4;
grid.ColumnSpacing = 4;

place(uilabel(grid, Text = "Image"), 1, 1);

obj.VariantDropDown = uidropdown(grid, ...
    Items = ["Projection", "Mid plane", "Composite", "Raw"], ...
    ItemsData = {"proj", "mid", "composite", "raw"}, ...
    Value = "proj", ...
    ValueChangedFcn = @(~,~) obj.onDisplayOptionChanged());
place(obj.VariantDropDown, 1, 2);
obj.VariantDropDown.Tooltip = "Which rendition of each section to display.";

place(uilabel(grid, Text = "Channel"), 1, 3);

obj.ChannelDropDown = uidropdown(grid, ...
    Items = "Channel 1", ...
    ItemsData = {1}, ...
    ValueChangedFcn = @(~,~) obj.onDisplayOptionChanged());
place(obj.ChannelDropDown, 1, 4);
obj.ChannelDropDown.Tooltip = "Page of a multi-channel TIFF, or an RGB merge of the first channels.";

place(uilabel(grid, Text = "Colormap"), 1, 5);

obj.ColormapDropDown = uidropdown(grid, ...
    Items = ["gray", "bone", "hot", "parula", "turbo", "green", "magenta"], ...
    Value = "gray", ...
    ValueChangedFcn = @(~,~) obj.onColormapChanged());
place(obj.ColormapDropDown, 1, 6);
obj.ColormapDropDown.Tooltip = "Colormap for single channel images. " + ...
    "The choice is remembered for the stain on screen and comes back with it.";

place(uilabel(grid, Text = "Contrast %"), 1, 7);

obj.LowPercentileField = uieditfield(grid, "numeric", ...
    Value = 0.5, ...
    Limits = [0 100], ...
    ValueChangedFcn = @(~,~) obj.onDisplayOptionChanged());
place(obj.LowPercentileField, 1, 8);
obj.LowPercentileField.Tooltip = "Lower display percentile.";

obj.HighPercentileField = uieditfield(grid, "numeric", ...
    Value = 99.7, ...
    Limits = [0 100], ...
    ValueChangedFcn = @(~,~) obj.onDisplayOptionChanged());
place(obj.HighPercentileField, 1, 9);
obj.HighPercentileField.Tooltip = "Upper display percentile.";

place(uilabel(grid, Text = "Max tiles"), 1, 10);

obj.MaxTilesField = uieditfield(grid, "numeric", ...
    Value = 12, ...
    Limits = [1 64], ...
    RoundFractionalValues = "on", ...
    ValueChangedFcn = @(~,~) obj.onDisplayOptionChanged());
place(obj.MaxTilesField, 1, 11);
obj.MaxTilesField.Tooltip = "Upper bound on images drawn at once; extra selections are reported, not drawn.";

% A section on a dark ground reads very differently from the same section on a
% white one, so the backdrop the tiles sit on is a display choice like the
% colormap rather than a fixed part of the window. The controls share the last
% three columns with the buttons on the row below rather than adding columns of
% their own, which is what keeps the panel inside the window.
backgroundLabel = uilabel(grid, Text = "Background");
backgroundLabel.HorizontalAlignment = "right";
place(backgroundLabel, 1, 12);

% The list itself is filled with the color in use, so it doubles as the swatch.
% SYNCBACKGROUNDCONTROLS owns Items, ItemsData, and Value from here on.
obj.BackgroundDropDown = uidropdown(grid, ...
    Items = obj.BackgroundNames, ...
    ItemsData = num2cell(obj.BackgroundCodes), ...
    Value = "lightgray", ...
    ValueChangedFcn = @(~,~) obj.onImageBackgroundChanged());
place(obj.BackgroundDropDown, 1, [13 14]);
obj.BackgroundDropDown.Tooltip = "Color behind the image tiles.";

obj.ShowRoiCheck = uicheckbox(grid, ...
    Text = "Line ROI", ...
    Value = true, ...
    ValueChangedFcn = @(~,~) obj.onDisplayOptionChanged());
place(obj.ShowRoiCheck, 2, [1 2]);
obj.ShowRoiCheck.Tooltip = "Draw the Fiji line ROI used to sample the profile." ...
    + obj.shortcutHint("toggleRoiOverlay");

obj.ShowBandCheck = uicheckbox(grid, ...
    Text = "Sampling band", ...
    Value = true, ...
    ValueChangedFcn = @(~,~) obj.onDisplayOptionChanged());
place(obj.ShowBandCheck, 2, [3 4]);
obj.ShowBandCheck.Tooltip = "Outline the full line width the profile averages over." ...
    + obj.shortcutHint("toggleBandOverlay");

obj.ColorByIntensityCheck = uicheckbox(grid, ...
    Text = "Shade ROI by intensity", ...
    Value = true, ...
    ValueChangedFcn = @(~,~) obj.onDisplayOptionChanged());
place(obj.ColorByIntensityCheck, 2, [5 6]);
obj.ColorByIntensityCheck.Tooltip = "Color the ROI using the matching *values.csv intensities." ...
    + obj.shortcutHint("toggleIntensityShading");

place(uilabel(grid, Text = "Profiles"), 2, 7);

obj.ProfileLayoutDropDown = uidropdown(grid, ...
    Items = obj.ProfileLayoutNames, ...
    ItemsData = num2cell(obj.ProfileLayoutCodes), ...
    Value = "bottom", ...
    ValueChangedFcn = @(~,~) obj.onLayoutOptionChanged());
place(obj.ProfileLayoutDropDown, 2, [8 9]);
obj.ProfileLayoutDropDown.Tooltip = "Where the profile plot sits relative to the image tiles.";

place(uilabel(grid, Text = "Size %"), 2, 10);

obj.ProfileSizeField = uieditfield(grid, "numeric", ...
    Value = 33, ...
    Limits = [5 95], ...
    RoundFractionalValues = "on", ...
    ValueChangedFcn = @(~,~) obj.onLayoutOptionChanged());
place(obj.ProfileSizeField, 2, 11);
obj.ProfileSizeField.Tooltip = "Share of the split the profile plot takes, in percent.";

obj.NewFigureButton = uibutton(grid, "push", ...
    Text = "Open in Figure", ...
    ButtonPushedFcn = @(~,~) obj.onOpenInFigure());
place(obj.NewFigureButton, 2, 13);
obj.NewFigureButton.Tooltip = "Redraw the current view in a normal figure." ...
    + obj.shortcutHint("openInFigure");

obj.ExportButton = uibutton(grid, "push", ...
    Text = "Export View", ...
    ButtonPushedFcn = @(~,~) obj.onExportView());
place(obj.ExportButton, 2, 14);
obj.ExportButton.Tooltip = "Save the current view to an image file." ...
    + obj.shortcutHint("exportView");

build_roi_edit_row(obj, grid);
build_surface_row(obj, grid);
build_profile_row(obj, grid);

end

function build_surface_row(obj, grid)
%BUILD_SURFACE_ROW Build the controls that mark the brain surface on a line.
% A row of its own under the ROI edit row it belongs to, because that row has
% no width left in it and because these four are one question -- where on this
% line does the brain start -- rather than four settings that happen to be
% adjacent. They read left to right as the order they are used in: switch the
% marks on, let the profile place one, place one by hand, take one off.
%
% Only the switch applies with nothing being edited. The other three change a
% line, and a line is only changeable inside an edit session, so
% UPDATEROIEDITCONTROLS greys them the way it greys Save and Revert.

% The one overlay switch with a callback of its own, because it is the one
% drawn on the profile plot as well as on the tiles.
obj.ShowSurfaceCheck = uicheckbox(grid, ...
    Text = "Brain surface", ...
    Value = true, ...
    ValueChangedFcn = @(~,~) obj.onSurfaceOverlayChanged());
place(obj.ShowSurfaceCheck, 4, [1 2]);
obj.ShowSurfaceCheck.Tooltip = "Tick each line where its brain surface was marked, " + ...
    "and rule the profile plot at the same depth." ...
    + obj.shortcutHint("toggleSurfaceOverlay");

obj.DetectSurfaceButton = uibutton(grid, "push", ...
    Text = "Detect", ...
    Enable = "off", ...
    ButtonPushedFcn = @(~,~) obj.onDetectSurface());
place(obj.DetectSurfaceButton, 4, [3 4]);
obj.DetectSurfaceButton.Tooltip = "Find the brain surface in the profile under the line, " + ...
    "where it steps up out of the background." ...
    + obj.shortcutHint("detectSurface");

obj.MarkSurfaceButton = uibutton(grid, "push", ...
    Text = "Mark Surface", ...
    Enable = "off", ...
    ButtonPushedFcn = @(~,~) obj.onMarkSurface());
place(obj.MarkSurfaceButton, 4, [5 6]);
obj.MarkSurfaceButton.Tooltip = "Click on the image to place the brain surface; " + ...
    "the point is taken onto the line." + obj.shortcutHint("markSurface");

obj.ClearSurfaceButton = uibutton(grid, "push", ...
    Text = "Clear", ...
    Enable = "off", ...
    ButtonPushedFcn = @(~,~) obj.onClearSurface());
place(obj.ClearSurfaceButton, 4, [7 8]);
obj.ClearSurfaceButton.Tooltip = "Take the brain surface mark off this line. " + ...
    "Save ROI then removes it from disk.";

obj.SurfaceLabel = uilabel(grid, Text = "");
place(obj.SurfaceLabel, 4, [9 14]);
obj.SurfaceLabel.FontColor = [0.35 0.35 0.35];

end

function build_profile_row(obj, grid)
%BUILD_PROFILE_ROW Build the controls that rescale the profile plot.
% A row of their own rather than a place beside the layout dropdown above,
% because these are the only display settings that change the numbers on an
% axis rather than the pixels in a tile, and because there are three of them:
% what the intensity axis is put through, what that is measured over, and what
% the distance axis is put through. They cost the panel a row and no width,
% which is the resource the three rows above have already spent.
%
% The row reads left to right as the sentence it is: normalize <this> over
% <that>, distance <this>.

place(uilabel(grid, Text = "Normalize"), 5, 1);

obj.ProfileNormDropDown = uidropdown(grid, ...
    Items = obj.ProfileNormNames, ...
    ItemsData = num2cell(obj.ProfileNormCodes), ...
    Value = "none", ...
    ValueChangedFcn = @(~,~) obj.onProfileOptionChanged());
place(obj.ProfileNormDropDown, 5, [2 3]);
obj.ProfileNormDropDown.Tooltip = "Rescale the intensity axis of the profile plot. " + ...
    "The plot only; the values files and everything exported from the app " + ...
    "stay in the units they were measured in.";

scopeLabel = uilabel(grid, Text = "over");
scopeLabel.HorizontalAlignment = "right";
place(scopeLabel, 5, 4);

obj.ProfileScopeDropDown = uidropdown(grid, ...
    Items = obj.ProfileScopeNames, ...
    ItemsData = num2cell(obj.ProfileScopeCodes), ...
    Value = "each", ...
    ValueChangedFcn = @(~,~) obj.onProfileOptionChanged());
place(obj.ProfileScopeDropDown, 5, [5 6]);
obj.ProfileScopeDropDown.Tooltip = "Whether each trace is scaled by its own numbers, " + ...
    "which hides how bright one section was against another, or every trace " + ...
    "by one set taken over the whole plot, which keeps that difference.";

place(uilabel(grid, Text = "Distance"), 5, 7);

obj.ProfileDistanceDropDown = uidropdown(grid, ...
    Items = obj.ProfileDistanceNames, ...
    ItemsData = num2cell(obj.ProfileDistanceCodes), ...
    Value = "none", ...
    ValueChangedFcn = @(~,~) obj.onProfileOptionChanged());
place(obj.ProfileDistanceDropDown, 5, [8 9]);
obj.ProfileDistanceDropDown.Tooltip = "Rescale the distance axis, to line the traces up " + ...
    "at their starts or to read them as a percentage of each line's own length.";

end

function build_roi_edit_row(obj, grid)
%BUILD_ROI_EDIT_ROW Build the controls that move a line ROI and save it back.
% Editing writes over the .roi file and the values.csv beside it, so the
% controls that do it sit together on their own row rather than among the
% display options, and the hint says what Save will touch.

obj.EditRoiButton = uibutton(grid, "state", ...
    Text = "Edit ROI", ...
    ValueChangedFcn = @(~,~) obj.onToggleEditRoi());
place(obj.EditRoiButton, 3, [1 2]);
obj.EditRoiButton.Tooltip = "Drag the line ROI of the one selected section." ...
    + obj.shortcutHint("toggleEditRoi");

place(uilabel(grid, Text = "Width px"), 3, 3);

% The width applies to whatever line is drawn next, so it stays editable even
% when nothing is being edited, and it is remembered between sessions.
obj.RoiWidthField = uieditfield(grid, "numeric", ...
    Value = obj.DefaultRoiWidth, ...
    Limits = [1 20000], ...
    RoundFractionalValues = "on", ...
    ValueChangedFcn = @(~,~) obj.onRoiWidthChanged());
place(obj.RoiWidthField, 3, 4);
obj.RoiWidthField.Tooltip = "Width of the band the profile averages over, in pixels. " + ...
    "The Fiji macro's band is 994 um, which is about 600 px on these projections.";

obj.DrawRoiButton = uibutton(grid, "push", ...
    Text = "Draw Line", ...
    ButtonPushedFcn = @(~,~) obj.onDrawRoi());
place(obj.DrawRoiButton, 3, [5 6]);
obj.DrawRoiButton.Tooltip = "Drag on the image to place a new line at the width above." ...
    + obj.shortcutHint("drawRoi");

obj.SaveRoiButton = uibutton(grid, "push", ...
    Text = "Save ROI", ...
    Enable = "off", ...
    ButtonPushedFcn = @(~,~) obj.onSaveRoiEdits());
place(obj.SaveRoiButton, 3, [7 8]);
obj.SaveRoiButton.Tooltip = "Overwrite the .roi file and remeasure its values.csv." ...
    + obj.shortcutHint("saveRoi");

obj.RevertRoiButton = uibutton(grid, "push", ...
    Text = "Revert", ...
    Enable = "off", ...
    ButtonPushedFcn = @(~,~) obj.onRevertRoiEdits());
place(obj.RevertRoiButton, 3, [9 10]);
obj.RevertRoiButton.Tooltip = "Discard unsaved changes and reload the ROI from disk." ...
    + obj.shortcutHint("revertRoi");

% The grid rules the band in the band's own frame, which is only worth looking
% at while a line is being aimed, so its switch belongs on this row rather than
% among the overlay checkboxes above. It is paid for out of the hint label,
% which is a sentence and loses less by being two columns shorter than this row
% would by spilling into a fourth one.
obj.ShowBandGridCheck = uicheckbox(grid, ...
    Text = "Band grid", ...
    Value = false, ...
    ValueChangedFcn = @(~,~) obj.onDisplayOptionChanged());
place(obj.ShowBandGridCheck, 3, [11 12]);
obj.ShowBandGridCheck.Tooltip = "While the ROI is being edited, rule the sampling band " + ...
    "parallel and square to the line, to check it against a layer boundary.";

obj.RoiEditLabel = uilabel(grid, Text = "");
place(obj.RoiEditLabel, 3, [13 14]);
obj.RoiEditLabel.FontColor = [0.35 0.35 0.35];

end

function place(component, row, column)
%PLACE Assign an explicit grid position to a component.

component.Layout.Row = row;
component.Layout.Column = column;

end
