function buildDatasetMenu(obj)
%BUILDDATASETMENU Build the Dataset menu on the figure menu bar.
% The root folder, the tracker CSV, and the load action used to take a panel
% across the top of the window; they are chosen once per sitting, so they live
% on a menu now and the freed row goes to the catalog and the image tiles.
% uifigure menus ignore the Accelerator property, so the one key this menu
% offers is bound on the figure in ONFIGUREKEYPRESS and only named here.

obj.DatasetMenu = uimenu(obj.Fig, Text = "Dataset");

obj.RootFolderMenu = uimenu(obj.DatasetMenu, ...
    Text = "Root Folder:  (none selected)", ...
    MenuSelectedFcn = @(~,~) obj.onBrowseRoot());

obj.MetadataMenu = uimenu(obj.DatasetMenu, ...
    Text = "Tracker CSV:  (none)", ...
    MenuSelectedFcn = @(~,~) obj.onBrowseMetadata());

obj.ClearMetadataMenu = uimenu(obj.DatasetMenu, ...
    Text = "Clear Tracker CSV", ...
    Enable = "off", ...
    MenuSelectedFcn = @(~,~) obj.onClearMetadata());

% The tracker can also be read straight from the published copy of the sheet it
% is kept in, which saves exporting it by hand every time it changes. Both are
% offered because they suit different situations: the published copy is current
% and needs no file, the CSV needs no network.
obj.PublishedSheetMenu = uimenu(obj.DatasetMenu, ...
    Text = "Published Sheet:  (none)", ...
    Separator = "on", ...
    MenuSelectedFcn = @(~,~) obj.onSetPublishedSheet());

obj.ClearPublishedSheetMenu = uimenu(obj.DatasetMenu, ...
    Text = "Clear Published Sheet", ...
    Enable = "off", ...
    MenuSelectedFcn = @(~,~) obj.onClearPublishedSheet());

obj.LoadMenu = uimenu(obj.DatasetMenu, ...
    Text = "Load Dataset" + obj.shortcutHint("loadDataset"), ...
    Separator = "on", ...
    MenuSelectedFcn = @(~,~) obj.onLoadData());

% Placeholder labels are replaced as soon as the paths are known.
obj.refreshDatasetMenu();

end
